fastify/fastify-cookie

plugin.js, test/cookie.test.js
It is currently not possible to set multiple cookies with `fastify-cookie`. Each call of `setCookie(name, value, options)` overrides the `Set-Cookie` header set by the previous call.
In the following example only the second cookie is set:
```js
fastify.get('/', (req, reply) => {
reply
.setCookie('foo', 'foo')
.setCookie('bar', 'test')
.send({hello: 'world'})
})
```
This PR fixes this problem.
=> Fix handling of multiple cookies

package.json
For now, people who installed `fastify-cookie` and use Typescript would see a compiler error: 
```
error TS7016: Could not find a declaration file for module 'cookie'.
Try `npm install @types/cookie` if it exists or add a new declaration (.d.ts) file containing `declare module 'cookie';`
```
Move `@types/cookie` from devDependencies to dependencies can fix this error.
=> move `@types/cookie` from devDependencies to dependencies

package.json, plugin.d.ts, test/types.test.ts
- Add `CookieSerializeOptions`
- Small fixes in `package.json`
@jsumners pick your poison 😈 😄
=> Update typescript definitions

plugin.d.ts, test/types.test.ts
Addresses #17 
Replaces areas in which the HTTP request, response, and server types are taken and extends them to accept HTTP2 types.
=> Extend plugin types to accept HTTP2 request/response/server types

Readme.md, plugin.js, test/cookie.test.js
Now that Fastify v2 exists, we can hook in at the correct part of the lifecycle. This PR does that.
=> Use onRequest instead of preHandler

plugin.js
With fastify-cookie v3.0, Fastify v2.0 is required, so the minimum version needs to be updated.
=> Update minimum version passed to fastify-plugin

Readme.md, plugin.js, test/cookie.test.js
https://github.com/fastify/fastify-cookie/issues/48
Add `parseOption` (better name is welcomed) option to allow passing options to `cookie.parse()`.
And replace an unneeded conditional operator with an `if` statement.
=> Pass option to cookie parse

plugin.d.ts, test/types.test.ts
https://github.com/fastify/fastify-cookie/issues/61: Add "none" option for the CookieSerializeOptions.sameSite parameter as specified in https://www.npmjs.com/package/cookie#options-1
=> Add 'none' option to CookieSerializeOptions.sameSite

package.json, plugin.d.ts, test/cookie.test.js
As titled, unfortunately rc.4 shipped a few incompatibilities on the types.
=> Updated to rc.4

README.md, plugin.js, test/cookie.test.js
Hi there,
I added this decorator to help me decrypt cookies/sessions when using `fastify-websocket` (see https://github.com/fastify/fastify-websocket/issues/70) , since wsHandlers don't have access to the `FastifyRequest ` you have to manually decrypt cookies/sessions. I've already submitted a PR to `fastify-session` to be able to decrypt sessions manually here https://github.com/SerayaEryn/fastify-session/pull/128.
However I would like to parse the cookie manually without pulling in the `cookie` package and duplicating `options` logic in two locations, hence this added decorator to make this step a little easier
=> feat: add decorator to manually parse cookies

README.md, package.json, plugin.js, signer.js, test/cookie.test.js, test/signer.test.js
Adds a custom signer support. 
=> feat: Allow passing a custom signer

plugin.d.ts, test/plugin.test-d.ts
Resolve: #93 
Test cannot be added because there are no dependencies of ```fastify```, so the type cannot be tested
=> fix: unsignCookie return type (#93)

package.json, plugin.d.ts, plugin.js, test/plugin.test-d.ts
Introduces the "infamous triplet" for module exports.
Replaces deprecated FastifyPlugin type.
=> Make TS types more consistent with other fastify plugins

README.md, plugin.d.ts, plugin.js, test/cookie.test.js, test/plugin.test-d.ts
it makes express plugin compatible
=> duplicate setCookie for express plugin

README.md, plugin.js, test/cookie.test.js
Fixes #99 by decorating the fastify instance with an `unsignCookie` method
=> Decorate fastify instance with an `unsignCookie` method

plugin.d.ts, test/plugin.test-d.ts
Fixes https://github.com/fastify/fastify-cookie/issues/121 (I'm not quite sure how to test it though, but it works in my codebase 😄 )
=> Add missing unsignCookie function signature to the FastifyInstance interface

package.json, plugin.d.ts, test/plugin.test-d.ts
Hello,
- fix: add `parseCookie` method types
- chore: upgrade package dependencies
- refactor: add a JSDoc link to the documentation
Closes https://github.com/fastify/fastify-cookie/issues/145
=> fix: add parseCookie method types

test/cookie.test.js
Hello.
- Remove `preParsing` references from tests (https://github.com/fastify/fastify/issues/3503)
=> test: prepare plugin for fastify 4.x

plugin.d.ts, plugin.js, test/cookie.test.js, test/plugin.test-d.ts
Add `parseOptions` type definitions to `FastifyCookieOptions` interface and utilize options in `setCookie` function.
=> Add parseOptions object to FastifyCookieOptions

package.json, test/cookie.test.js
Hello.
Following [this discussion](https://github.com/fastify/fastify/issues/3503), this PR aims to :
- add back `preParsing` hook tests
- upgrade package dependencies
=> test: add back `preParsing` hook tests

.taprc, package.json, plugin.d.ts, test/plugin.test-d.ts
Hello.
This PR aims to :
- return `this` instead of `FastifyReply` to avoid reply typings re-initialization and allow reply decorators chaining (fix https://github.com/fastify/fastify-cookie/issues/166)
- update `.taprc` configuration file and add some npm scripts
- upgrade package dependencies
=> fix (types): return `this` instead of `FastifyReply`

plugin.d.ts, test/plugin.test-d.ts
The current type definitions do not allow providing a custom signing object (as documented in the [README](https://github.com/fastify/fastify-cookie#custom-cookie-signer))
=> Adjust secret type to allow custom signer

README.md
Changed the import to a type-only import, which is better practice in typescript.
=> Improve typescript example in README

plugin.d.ts, test/cookie.test.js, test/plugin.test-d.ts
Updates the TypeScript types to add `| undefined` to a request's cookies. 
This is a breaking change as previously cookies were typed to be a string, while now that cannot be assumed. (Possibly 7.1.0?)
=> Update Request Cookies Type to Add `undefined`

README.md, plugin.d.ts, test/plugin.test-d.ts
Have fixed type definition for the last release
=> fix: plugin type definition

README.md, plugin.d.ts, plugin.js, test/cookie.test.js
This functionality is basically taken from @fastify/session https://github.com/fastify/session/blob/b1fc11c6fbb16c63a1884f202fcd030ecdb18a07/lib/cookie.js#L17
On the long run, we can remove the cookie class from @fastify/session.
=> add secure: 'auto' Option

README.md, package.json, plugin.js, test/cookie.test.js, types/plugin.d.ts, types/plugin.test-d.ts
This PR does not set the sign and unsign decorators, when a secret is not set. 
This makes it possible to feature detect if a secret was purposefully set. If somebody used signing and unsigning with no secret, the person can still provide an empty string as secret.
I assume this is a major.
=> feat: sign and unsign decorators are not set, when secret-option is undefined

README.md, package.json, plugin.js, test/cookie.test.js, types/plugin.d.ts, types/plugin.test-d.ts
Hi!
Sometimes you need to receive cookies in the middleware, and then repeated parsing in the onRequest phase will be superfluous. The "addHookOnRequest: false" option can disable adding a hook, leaving all other functionality.
- [*] run `npm run test` and `npm run benchmark`
- [*] tests and/or benchmarks are included
- [*] documentation is changed or added
- [*] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
=> feat: option disabling parsing in the onRequest phase

types/plugin.test-d.ts
=> test(types): remove unused imports

types/plugin.d.ts
Fixing typo in [fastify-cookie/typesplugin.d.ts](https://github.com/fastify/fastify-cookie/blob/37bd8409c0d99ee9558f7f485edc56b5bcd1d696/types/plugin.d.ts#L121). 
See [Issue 235](https://github.com/fastify/fastify-cookie/issues/235)
=> Fix typo from 'node' to 'none' in CookieSerializeOptions for sameSite attribute

plugin.js, test/cookie.test.js
This commits fixes the `@fastify/session` module that was broken due to the changes introduced in https://github.com/fastify/fastify-cookie/pull/237 (v9.0.0).
The problem is that the `onSend` hook installed by `@fastify/cookie` was firing before the `onSend` hook in `@fastify/session`, essentially not sending the cookie added by `@fastify/session`.
I added a tiny provision for this case.
=> Fix @fastify/session

signer.js
We know that `secrets` is an array – so using a `for` loop is always going to be faster than iterators
Random reference: https://twitter.com/oneshadab/status/1643673793104158726
=> use for loop instead of for...of

plugin.js, test/cookie.test.js
We have to keep flushing after our onSend hook ran, because we just don't know if setCookie will get called again or that was the last time
Not reassigning the Map is probably less costly though
@Uzlopak @mcollina 
=> Check if onSend was ran and keep resetting the map

plugin.js
95% of the time, the header will not be defined when cookies are set, so there is no need to call removeHeader unless needed
Also, the setCookies function itself now resets the Map, which makes it easier to reason about what's going on
Median of 5 tests for 5 cookies
Old:
```shell
100 connections
┌─────────┬──────┬──────┬───────┬──────┬─────────┬─────────┬────────┐
│ Stat    │ 2.5% │ 50%  │ 97.5% │ 99%  │ Avg     │ Stdev   │ Max    │
├─────────┼──────┼──────┼───────┼──────┼─────────┼─────────┼────────┤
│ Latency │ 1 ms │ 1 ms │ 2 ms  │ 3 ms │ 1.06 ms │ 0.72 ms │ 120 ms │
└─────────┴──────┴──────┴───────┴──────┴─────────┴─────────┴────────┘
┌───────────┬───────┬───────┬─────────┬───────┬──────────┬────────┬───────┐
│ Stat      │ 1%    │ 2.5%  │ 50%     │ 97.5% │ Avg      │ Stdev  │ Min   │ …
```
=> perf: only call removeHeader when needed

plugin.js, test/cookie.test.js
Fixes https://github.com/fastify/fastify-cookie/issues/246
=> Fix support for response that does not set a cookie

plugin.js
Small change where the `request.cookies` is no longer initialized (NEW, L56) before checking if the cookie header is set. Saves us an empty object creation if the header exists
=> perf: don't initialize req.cookies before checking the header

signer.js, test/cookie.test.js, test/signer.test.js
Same as https://github.com/fastify/fastify-static/pull/407
Not sure if destructuring would help as well since it's the `crypto` module
=> perf: use `node:` prefix for builtins

plugin.js
=> use named exports

plugin.js
See https://github.com/fastify/fastify-helmet/issues/236
=> refactor(plugin): replace `typeof` undefined check

README.md, cookie.js, test/cookie.test.js, types/plugin.d.ts, types/plugin.test-d.ts
Adds support for the non-standard `Partitioned` option
It was added to jshttp/cookie [a few days ago](https://github.com/jshttp/cookie/pull/153)
=> feat: add partitioned

README.md, cookie.js, plugin.js, test/cookie-module.test.js, types/plugin.d.ts, types/plugin.test-d.ts
This way we can use it in fastify/secure-session and co instead of the cookie package.
=> export integrated cookie functionality

plugin.js, test/cookie.test.js, types/plugin.d.ts
This case was missing from the tests, the function is also easier to understand now in my opinion
=> refactor setCookies and remove istanbul ignore else

cookie.js
Important change is at line 70, if we don't have any `=` left in the string, no need to continue the loop as we do not have any key-value pairs left
=> cookie parse: add fast path
