fastify/fastify-cookie

package.json, plugin.js, test/cookie.test.js
This PR adds plugin metadata to `fastify-cookie`.
Updates the dependency `fastify-plugin` to Version `0.2.1`.
Updates the dev dependency `fastify` to Version `0.37.0`.
=> Add plugin metadata

.travis.yml, plugin.d.ts, test/types.test.ts
This PR fixes `plugin.d.ts` and type test. 😃 
- Fix `plugin.d.ts` definition
- Fix test cases of typescript
- Add typescript compilation test to CI
=> fix(types): `setCookie()` should return `FastifyReply<HttpResponse>`

Readme.md
=> Callback remove from docs

Readme.md, package.json, plugin.d.ts, plugin.js, test/cookie.test.js
Added:
Dependency: "cookie-signature" to sign cookie values;
Optional "secret" property of plugin options to provide a signature secret;
Property in options of setCookie function that determines if a cookie have to be signed, this property is deleted after value be signed;
Function "unsignValue" to get value and validation of a signed cookie
Tests
=> Signature support

plugin.js, test/cookie.test.js
=> Fix issue 53

package.json, test/cookie.test.js
=> #57 - Moved tests over to use fastify inject

.github/workflows/ci.yml
Hey @jsumners! This PR closes #56 🙂
=> Remove unsupported Node.js LTS versions

plugin.d.ts, test/types.test.ts
There was no benchmark command but tests pass. Just a type addition but here you go!
```
test/cookie.test.js ................................. 65/65
total ............................................... 65/65
65 passing (470.467ms)
```
=> add `unsignCookie` method type on reply

README.md
=> Fix the description of setting method options

README.md
=> add dot in README example

plugin.js
=> Use request.raw instead of request.req

plugin.js
The problem described in #86 can be fixed by using an arrow function to break the binding of this to the Fastify Request instance.
See https://www.fastify.io/docs/latest/Decorators/#decoraterequestname-value-dependencies
Fixes https://github.com/fastify/help/issues/333
=> fix: Issue #86 by using  null

README.md
=> chore: remove outdated readme badge

README.md, package.json, plugin.js, signer.js, test/cookie.test.js, test/signer.test.js
=> feat: key rotation

plugin.js, test/cookie.test.js
=> feat: allow share cookie options for setCookie and clearCookie

README.md
=> chore: update docs about cookie security

README.md, plugin.d.ts, plugin.js, test/cookie.test.js, test/plugin.test-d.ts
=> Unsign cookie via request object

README.md
This PR should help developers running into #38 
=> docs: provide a ts example

README.md
This just fixes a minor typo from unsing to unsign in the readme. No code change associated with it, so no new tests needed, and tests shouldn't need to be run.
=> Fix minor typo in README.

README.md
Adds an *Installation* section on the README.md. 
Make more visible to developers the difference between current ([ad]fastify/cookie) v6 npm package name with older (fastify-cookie) v5.
=> Update README.md with quick install access

.github/workflows/ci.yml, package.json, plugin.js
=> Updated to Fastify v4

plugin.d.ts, test/plugin.test-d.ts
cookie v. 0.5.0 adds priority option. this adds the corresponding typings
=> chore: add priority to cookie typings

.github/workflows/ci.yml
=> activate license-check

signer.js
=> fix lgtm alert. use randomBytes instead of hardcoded dummyHmac

plugin.js, test/cookie.test.js
Resolve: https://github.com/fastify/fastify-cookie/issues/211
=> fix: Include parseOptions in the clearCookie function

README.md, plugin.js, signer.js, test/signer.test.js, types/plugin.d.ts, types/plugin.test-d.ts
=> Add support for Buffer secrets (#214)

types/plugin.d.ts
=> fix(docs): msecs to seconds (#219)

plugin.js
Apologies, was trying to get the last one out fast and I missed this
=> perf: only clear map when it's populated

signer.js
See https://github.com/fastify/fastify-autoload/pull/330
=> refactor(signer): add `u` unicode flag to regex

cookie.js, package.json, plugin.js, test/cookie-module.test.js
This is to enable https://github.com/fastify/session/issues/213 to be fixed in this module.
=> Go back to use our own cookie implementation
